### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by vjdobermann** [projectgus/hairless-midiserial#45]
Hi everybody,
I'm trying to use Hairless and I've got an error message "Error: got unexpected data byte 0x4b."
see my capture screen here [https://www.dbr-prod.ch/images/capture_hairless2.png](url)

the code in the arduino is the basic one founded in the video tutorial : 
`#include <MIDI.h>

#define LED 13

// Created and binds the MIDI interface to the default hardware Serial port
 MIDI_CREATE_DEFAULT_INSTANCE();  

void setup()
{
    
    pinMode(LED, OUTPUT);
    MIDI.begin(MIDI_CHANNEL_OFF); // pas d'entrée midi
}

void loop()
{
  digitalWrite(LED, 1);
  MIDI.sendNoteOn(60, 60, 1);
  delay(1000);
  MIDI.sendNoteOff(60, 0, 1);
  delay(1000);
}`

could someone help me please ?

Great thanks in advance

**Comment by SkinyMonkey** [comment]
Could be:

https://github.com/projectgus/hairless-midiserial/issues/16

Check it.

**Comment by vjdobermann** [comment]
Hey, do you have the same issue ?
I was working on this project at summer 2017^^ I've do dig my cave to find how this issue has been solved xD

**Comment by JiffiPop** [comment]
Yes I am having the same issue, how'd your project go?  I'm extremely new to arduino, so I am using somebody else's code, but I still cannot get it to work.
